# -*- coding: utf-8 -*-
"""emwa_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smpCsZSX2TeV0zfRj3WKKMIkD8txgqdY

**EMWA Model**
"""

import pandas as pd
import numpy as np
from pathlib import Path
import warnings

warnings.filterwarnings('ignore')
Path('results').mkdir(exist_ok=True)

class EWMAModel:
    def __init__(self, lambda_param=0.94):
        self.lambda_param = lambda_param

    def load_data(self, ticker):
        filepath = f"data/processed/{ticker}_processed.csv"
        df = pd.read_csv(filepath, index_col=0, parse_dates=True)
        return df

    def split_data(self, df):
        n = len(df)
        train_end = int(n * 0.6)
        val_end = train_end + int(n * 0.2)
        return {
            'train': df.iloc[:train_end],
            'val': df.iloc[train_end:val_end],
            'test': df.iloc[val_end:]
        }

    def calculate_ewma_volatility(self, returns, lambda_param=None):
        if lambda_param is None:
            lambda_param = self.lambda_param
        squared_returns = returns ** 2
        initial_vol = squared_returns.iloc[:20].std() ** 2
        variance = np.zeros(len(returns))
        variance[0] = initial_vol
        for t in range(1, len(returns)):
            variance[t] = lambda_param * variance[t-1] + (1 - lambda_param) * squared_returns.iloc[t-1]
        volatility = np.sqrt(variance) * np.sqrt(252)
        return pd.Series(volatility, index=returns.index)

    def train_and_evaluate(self, ticker):
        print(f"EWMA for {ticker}...", end=" ")

        try:
            df = self.load_data(ticker)
            splits = self.split_data(df)

            train_returns = df['log_return'].iloc[:len(splits['train'])].dropna()
            test_actual_vol = splits['test']['realized_vol_20d'].dropna()

            test_forecast_vol = []
            for i in range(len(splits['test'])):
                try:
                    subset = df['log_return'].iloc[:len(splits['train']) + len(splits['val']) + i].dropna()
                    ewma_vol = self.calculate_ewma_volatility(subset, lambda_param=0.94)
                    test_forecast_vol.append(ewma_vol.iloc[-1])
                except:
                    test_forecast_vol.append(np.nan)

            test_forecast_vol = pd.Series(test_forecast_vol, index=splits['test'].index)

            forecast_df = pd.DataFrame({
                'test_actual': test_actual_vol,
                'test_forecast': test_forecast_vol
            })
            forecast_df.to_csv(f'results/{ticker}_ewma_forecast.csv')
            print("✓")

        except Exception as e:
            print(f"✗ {str(e)[:60]}")

ewma = EWMAModel()
for ticker in ['SPY', 'AAPL', 'BTC-USD']:
    ewma.train_and_evaluate(ticker)

print("\n✓ EWMA modeling complete - forecasts saved to results/")