# -*- coding: utf-8 -*-
"""garch_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smpCsZSX2TeV0zfRj3WKKMIkD8txgqdY

**GARCH Model**
"""

import subprocess
import sys
subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "arch"])

import pandas as pd
import numpy as np
from pathlib import Path
import warnings
from arch import arch_model

warnings.filterwarnings('ignore')

Path('results').mkdir(exist_ok=True)

class GARCHModel:
    def load_data(self, ticker):
        filepath = f"data/processed/{ticker}_processed.csv"
        df = pd.read_csv(filepath, index_col=0, parse_dates=True)
        return df

    def split_data(self, df):
        n = len(df)
        train_end = int(n * 0.6)
        val_end = train_end + int(n * 0.2)
        return {
            'train': df.iloc[:train_end],
            'val': df.iloc[train_end:val_end],
            'test': df.iloc[val_end:]
        }

    def fit_garch(self, returns):
        returns_pct = returns * 100
        model = arch_model(returns_pct, vol='Garch', p=1, q=1, rescale=True)
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            result = model.fit(disp='off')
        return result

    def train_and_evaluate(self, ticker):
        print(f"GARCH for {ticker}...", end=" ")

        try:
            df = self.load_data(ticker)
            splits = self.split_data(df)

            train_returns = splits['train']['log_return'].dropna()
            test_df = splits['test'].copy()

            model_result = self.fit_garch(train_returns)

            conditional_vol = model_result.conditional_volatility
            last_vol = conditional_vol.iloc[-1] / 100
            vol_forecast = last_vol * np.sqrt(252)

            forecast_values = [vol_forecast] * len(test_df)

            actual_values = test_df['realized_vol_20d'].values

            forecast_df = pd.DataFrame({
                'test_actual': actual_values,
                'test_forecast': forecast_values
            }, index=test_df.index)

            forecast_df.to_csv(f'results/{ticker}_garch_forecast.csv')
            print("✓")

        except Exception as e:
            print(f"✗ {str(e)[:60]}")
            import traceback
            traceback.print_exc()

garch = GARCHModel()
for ticker in ['SPY', 'AAPL', 'BTC-USD']:
    garch.train_and_evaluate(ticker)

print("\n✓ GARCH complete")