# -*- coding: utf-8 -*-
"""ML_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smpCsZSX2TeV0zfRj3WKKMIkD8txgqdY

**Machine Learning Model**
"""

import subprocess
import sys
subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "xgboost"])
subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "lightgbm"])
subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "scikit-learn"])

import pandas as pd
import numpy as np
from pathlib import Path
import warnings
import xgboost as xgb
import lightgbm as lgb
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error

warnings.filterwarnings('ignore')

Path('results').mkdir(exist_ok=True)

class MLVolatilityModel:
    def __init__(self, model_type='xgboost'):
        self.model_type = model_type
        self.scaler = StandardScaler()
        self.model = None

    def load_data(self, ticker):
        filepath = f"data/processed/{ticker}_features.csv"
        if not Path(filepath).exists():
            filepath = f"data/processed/{ticker}_processed.csv"
        df = pd.read_csv(filepath, index_col=0, parse_dates=True)
        return df

    def split_data(self, df):
        n = len(df)
        train_end = int(n * 0.6)
        val_end = train_end + int(n * 0.2)
        return {
            'train': df.iloc[:train_end],
            'val': df.iloc[train_end:val_end],
            'test': df.iloc[val_end:]
        }

    def create_features(self, df):
        features = []
        target_col = 'realized_vol_20d'

        feature_cols = [col for col in df.columns if col not in
                       ['open', 'high', 'low', 'close', 'volume', 'daily_return', 'log_return', target_col]]

        for col in feature_cols:
            if df[col].notna().sum() > 0:
                features.append(col)

        return features

    def prepare_data(self, df, features):
        X = df[features].fillna(df[features].mean())
        y = df['realized_vol_20d'].dropna()

        common_idx = X.index.intersection(y.index)
        X = X.loc[common_idx]
        y = y.loc[common_idx]

        return X, y

    def build_model(self):
        if self.model_type == 'xgboost':
            return xgb.XGBRegressor(
                n_estimators=100,
                max_depth=5,
                learning_rate=0.1,
                subsample=0.8,
                colsample_bytree=0.8,
                random_state=42,
                verbosity=0
            )
        else:
            return lgb.LGBMRegressor(
                n_estimators=100,
                max_depth=5,
                learning_rate=0.1,
                subsample=0.8,
                colsample_bytree=0.8,
                random_state=42,
                verbose=-1
            )

    def train_and_evaluate(self, ticker):
        print(f"\n{self.model_type.upper()} for {ticker}...", end=" ")

        try:
            df = self.load_data(ticker)
            splits = self.split_data(df)

            features = self.create_features(df)

            X_train, y_train = self.prepare_data(splits['train'], features)
            X_test, y_test = self.prepare_data(splits['test'], features)

            if len(X_train) < 10 or len(X_test) < 10:
                print("✗ Insufficient data")
                return

            X_train_scaled = self.scaler.fit_transform(X_train)
            X_test_scaled = self.scaler.transform(X_test)

            self.model = self.build_model()
            self.model.fit(X_train_scaled, y_train)

            test_forecast = self.model.predict(X_test_scaled)

            forecast_df = pd.DataFrame({
                'test_actual': y_test.values,
                'test_forecast': test_forecast
            }, index=y_test.index)

            forecast_df.to_csv(f'results/{ticker}_{self.model_type}_forecast.csv')

            mae = mean_absolute_error(y_test, test_forecast)
            rmse = np.sqrt(mean_squared_error(y_test, test_forecast))

            print(f"✓ MAE={mae:.4f}, RMSE={rmse:.4f}")

        except Exception as e:
            print(f"✗ {str(e)[:50]}")

print("\n" + "="*70)
print("ML VOLATILITY FORECASTING")
print("="*70)

xgb_model = MLVolatilityModel(model_type='xgboost')
lgb_model = MLVolatilityModel(model_type='lightgbm')

tickers = ['SPY', 'AAPL', 'BTC-USD']

print("\nTraining XGBoost models:")
for ticker in tickers:
    xgb_model.train_and_evaluate(ticker)

print("\nTraining LightGBM models:")
for ticker in tickers:
    lgb_model.train_and_evaluate(ticker)

print("\n" + "="*70)
print("✓ ML modeling complete - forecasts saved to results/")
print("="*70 + "\n")