# -*- coding: utf-8 -*-
"""time_series_volatility_analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smpCsZSX2TeV0zfRj3WKKMIkD8txgqdY

**GARCH Model**
"""

import subprocess
import sys
subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "arch"])

import pandas as pd
import numpy as np
from pathlib import Path
import warnings
from arch import arch_model

warnings.filterwarnings('ignore')

Path('results').mkdir(exist_ok=True)

class GARCHModel:
    def load_data(self, ticker):
        filepath = f"data/processed/{ticker}_processed.csv"
        df = pd.read_csv(filepath, index_col=0, parse_dates=True)
        return df

    def split_data(self, df):
        n = len(df)
        train_end = int(n * 0.6)
        val_end = train_end + int(n * 0.2)
        return {
            'train': df.iloc[:train_end],
            'val': df.iloc[train_end:val_end],
            'test': df.iloc[val_end:]
        }

    def fit_garch(self, returns):
        returns_pct = returns * 100
        model = arch_model(returns_pct, vol='Garch', p=1, q=1, rescale=True)
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            result = model.fit(disp='off')
        return result

    def train_and_evaluate(self, ticker):
        print(f"GARCH for {ticker}...", end=" ")

        try:
            df = self.load_data(ticker)
            splits = self.split_data(df)

            train_returns = splits['train']['log_return'].dropna()
            test_df = splits['test'].copy()

            model_result = self.fit_garch(train_returns)

            conditional_vol = model_result.conditional_volatility
            last_vol = conditional_vol.iloc[-1] / 100
            vol_forecast = last_vol * np.sqrt(252)

            forecast_values = [vol_forecast] * len(test_df)

            actual_values = test_df['realized_vol_20d'].values

            forecast_df = pd.DataFrame({
                'test_actual': actual_values,
                'test_forecast': forecast_values
            }, index=test_df.index)

            forecast_df.to_csv(f'results/{ticker}_garch_forecast.csv')
            print("✓")

        except Exception as e:
            print(f"✗ {str(e)[:60]}")
            import traceback
            traceback.print_exc()

garch = GARCHModel()
for ticker in ['SPY', 'AAPL', 'BTC-USD']:
    garch.train_and_evaluate(ticker)

print("\n✓ GARCH complete")

"""**EMWA Model**"""

import pandas as pd
import numpy as np
from pathlib import Path
import warnings

warnings.filterwarnings('ignore')
Path('results').mkdir(exist_ok=True)

class EWMAModel:
    def __init__(self, lambda_param=0.94):
        self.lambda_param = lambda_param

    def load_data(self, ticker):
        filepath = f"data/processed/{ticker}_processed.csv"
        df = pd.read_csv(filepath, index_col=0, parse_dates=True)
        return df

    def split_data(self, df):
        n = len(df)
        train_end = int(n * 0.6)
        val_end = train_end + int(n * 0.2)
        return {
            'train': df.iloc[:train_end],
            'val': df.iloc[train_end:val_end],
            'test': df.iloc[val_end:]
        }

    def calculate_ewma_volatility(self, returns, lambda_param=None):
        if lambda_param is None:
            lambda_param = self.lambda_param
        squared_returns = returns ** 2
        initial_vol = squared_returns.iloc[:20].std() ** 2
        variance = np.zeros(len(returns))
        variance[0] = initial_vol
        for t in range(1, len(returns)):
            variance[t] = lambda_param * variance[t-1] + (1 - lambda_param) * squared_returns.iloc[t-1]
        volatility = np.sqrt(variance) * np.sqrt(252)
        return pd.Series(volatility, index=returns.index)

    def train_and_evaluate(self, ticker):
        print(f"EWMA for {ticker}...", end=" ")

        try:
            df = self.load_data(ticker)
            splits = self.split_data(df)

            train_returns = df['log_return'].iloc[:len(splits['train'])].dropna()
            test_actual_vol = splits['test']['realized_vol_20d'].dropna()

            test_forecast_vol = []
            for i in range(len(splits['test'])):
                try:
                    subset = df['log_return'].iloc[:len(splits['train']) + len(splits['val']) + i].dropna()
                    ewma_vol = self.calculate_ewma_volatility(subset, lambda_param=0.94)
                    test_forecast_vol.append(ewma_vol.iloc[-1])
                except:
                    test_forecast_vol.append(np.nan)

            test_forecast_vol = pd.Series(test_forecast_vol, index=splits['test'].index)

            forecast_df = pd.DataFrame({
                'test_actual': test_actual_vol,
                'test_forecast': test_forecast_vol
            })
            forecast_df.to_csv(f'results/{ticker}_ewma_forecast.csv')
            print("✓")

        except Exception as e:
            print(f"✗ {str(e)[:60]}")

ewma = EWMAModel()
for ticker in ['SPY', 'AAPL', 'BTC-USD']:
    ewma.train_and_evaluate(ticker)

print("\n✓ EWMA modeling complete - forecasts saved to results/")

"""**GARCH v. EMWA**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import warnings

warnings.filterwarnings('ignore')

results_dir = Path('results')

print("\n" + "="*70)
print("GARCH vs EWMA COMPARISON")
print("="*70 + "\n")

tickers = ['SPY', 'AAPL', 'BTC-USD']
comparison_data = []

for ticker in tickers:
    garch_path = results_dir / f"{ticker}_garch_forecast.csv"
    ewma_path = results_dir / f"{ticker}_ewma_forecast.csv"

    print(f"Loading {ticker}...")

    if not garch_path.exists():
        print(f"  Warning: {garch_path} not found")
        continue
    if not ewma_path.exists():
        print(f"  Warning: {ewma_path} not found")
        continue

    garch_df = pd.read_csv(garch_path, index_col=0, parse_dates=True)
    ewma_df = pd.read_csv(ewma_path, index_col=0, parse_dates=True)

    print(f"  GARCH: {len(garch_df)} rows")
    print(f"  EWMA: {len(ewma_df)} rows")

    garch_df = garch_df.dropna()
    ewma_df = ewma_df.dropna()

    print(f"  After dropna - GARCH: {len(garch_df)}, EWMA: {len(ewma_df)}")

    common_idx = garch_df.index.intersection(ewma_df.index)
    print(f"  Common indices: {len(common_idx)}")

    if len(common_idx) == 0:
        print(f"  Skipping {ticker} - no common indices")
        continue

    garch_actual = garch_df.loc[common_idx, 'test_actual'].values
    garch_forecast = garch_df.loc[common_idx, 'test_forecast'].values
    ewma_actual = ewma_df.loc[common_idx, 'test_actual'].values
    ewma_forecast = ewma_df.loc[common_idx, 'test_forecast'].values

    garch_mae = np.mean(np.abs(garch_actual - garch_forecast))
    ewma_mae = np.mean(np.abs(ewma_actual - ewma_forecast))

    garch_rmse = np.sqrt(np.mean((garch_actual - garch_forecast)**2))
    ewma_rmse = np.sqrt(np.mean((ewma_actual - ewma_forecast)**2))

    garch_corr = np.corrcoef(garch_actual, garch_forecast)[0, 1]
    ewma_corr = np.corrcoef(ewma_actual, ewma_forecast)[0, 1]

    comparison_data.append({
        'Ticker': ticker,
        'GARCH_MAE': f"{garch_mae:.4f}",
        'EWMA_MAE': f"{ewma_mae:.4f}",
        'GARCH_RMSE': f"{garch_rmse:.4f}",
        'EWMA_RMSE': f"{ewma_rmse:.4f}",
        'GARCH_Corr': f"{garch_corr:.4f}",
        'EWMA_Corr': f"{ewma_corr:.4f}",
        'Better_MAE': 'EWMA' if ewma_mae < garch_mae else 'GARCH'
    })
    print(f"  ✓ Processed\n")

if comparison_data:
    comparison_df = pd.DataFrame(comparison_data)
    print(comparison_df.to_string(index=False))

    print("\n" + "="*70)
    print("DETAILED METRICS")
    print("="*70)

    for ticker in tickers:
        garch_path = results_dir / f"{ticker}_garch_forecast.csv"
        ewma_path = results_dir / f"{ticker}_ewma_forecast.csv"

        if not (garch_path.exists() and ewma_path.exists()):
            continue

        garch_df = pd.read_csv(garch_path, index_col=0, parse_dates=True).dropna()
        ewma_df = pd.read_csv(ewma_path, index_col=0, parse_dates=True).dropna()

        common_idx = garch_df.index.intersection(ewma_df.index)
        if len(common_idx) == 0:
            continue

        print(f"\n{ticker}:")
        print("-" * 70)

        ga = garch_df.loc[common_idx, 'test_actual'].values
        gf = garch_df.loc[common_idx, 'test_forecast'].values
        ea = ewma_df.loc[common_idx, 'test_actual'].values
        ef = ewma_df.loc[common_idx, 'test_forecast'].values

        gmae = np.mean(np.abs(ga - gf))
        emae = np.mean(np.abs(ea - ef))
        grmse = np.sqrt(np.mean((ga - gf)**2))
        ermse = np.sqrt(np.mean((ea - ef)**2))
        gcorr = np.corrcoef(ga, gf)[0, 1]
        ecorr = np.corrcoef(ea, ef)[0, 1]

        print(f"  MAE:     GARCH={gmae:.4f}  EWMA={emae:.4f}  Winner: {'EWMA' if emae < gmae else 'GARCH'}")
        print(f"  RMSE:    GARCH={grmse:.4f}  EWMA={ermse:.4f}  Winner: {'EWMA' if ermse < grmse else 'GARCH'}")
        print(f"  Corr:    GARCH={gcorr:.4f}  EWMA={ecorr:.4f}  Winner: {'EWMA' if ecorr > gcorr else 'GARCH'}")

    fig, axes = plt.subplots(2, 3, figsize=(18, 10))
    fig.suptitle('GARCH vs EWMA: Actual vs Forecast', fontsize=16, fontweight='bold')

    for idx, ticker in enumerate(tickers):
        garch_path = results_dir / f"{ticker}_garch_forecast.csv"
        ewma_path = results_dir / f"{ticker}_ewma_forecast.csv"

        if not (garch_path.exists() and ewma_path.exists()):
            continue

        garch_df = pd.read_csv(garch_path, index_col=0, parse_dates=True).dropna()
        ewma_df = pd.read_csv(ewma_path, index_col=0, parse_dates=True).dropna()

        common_idx = garch_df.index.intersection(ewma_df.index)
        if len(common_idx) == 0:
            continue

        actual = garch_df.loc[common_idx, 'test_actual']
        garch_fcst = garch_df.loc[common_idx, 'test_forecast']
        ewma_fcst = ewma_df.loc[common_idx, 'test_forecast']

        ax1 = axes[0, idx]
        ax1.plot(actual.index, actual.values, label='Actual', linewidth=2.5, color='black', alpha=0.8)
        ax1.plot(garch_fcst.index, garch_fcst.values, label='GARCH', linewidth=2, alpha=0.7, linestyle='--')
        ax1.plot(ewma_fcst.index, ewma_fcst.values, label='EWMA', linewidth=2, alpha=0.7, linestyle='-.')
        ax1.set_title(f'{ticker} - Time Series', fontweight='bold')
        ax1.set_ylabel('Volatility')
        ax1.legend()
        ax1.grid(True, alpha=0.3)

        ax2 = axes[1, idx]
        ax2.scatter(actual.values, garch_fcst.values, alpha=0.5, s=30, label='GARCH', color='blue')
        ax2.scatter(actual.values, ewma_fcst.values, alpha=0.5, s=30, label='EWMA', color='orange')
        min_val = min(actual.min(), garch_fcst.min(), ewma_fcst.min())
        max_val = max(actual.max(), garch_fcst.max(), ewma_fcst.max())
        ax2.plot([min_val, max_val], [min_val, max_val], 'r--', linewidth=2, alpha=0.5)
        ax2.set_xlabel('Actual Volatility')
        ax2.set_ylabel('Forecast Volatility')
        ax2.set_title(f'{ticker} - Accuracy', fontweight='bold')
        ax2.legend()
        ax2.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig('results/comparison_final.png', dpi=150, bbox_inches='tight')
    print("\n✓ Saved plots")
    plt.show()

    print("\n" + "="*70)
    print("SUMMARY")
    print("="*70)
    print("""
GARCH: Theoretically sophisticated, industry standard
EWMA: Simple, often beats GARCH on real data
Metrics: Lower MAE/RMSE = better, Higher Correlation = better
""")
    print("="*70 + "\n")
else:
    print("No data to compare")