# -*- coding: utf-8 -*-
"""data_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smpCsZSX2TeV0zfRj3WKKMIkD8txgqdY
"""

import yfinance as yf
import pandas as pd
import numpy as np
from pathlib import Path
import logging
from datetime import datetime, timedelta
import warnings

warnings.filterwarnings('ignore')

# Setup logging - force flush
logging.basicConfig(level=logging.INFO, format='%(message)s', force=True)
logger = logging.getLogger(__name__)

import sys
import io

# Ensure stdout/stderr are not buffered
class FlushPrint:
    def __call__(self, *args, **kwargs):
        print(*args, **kwargs)
        sys.stdout.flush()

class DataLoader:
    """
    Download and preprocess OHLCV data from Yahoo Finance.
    Handles missing data, outliers, and creates organized data structure.
    """

    def __init__(self, data_dir='data'):
        """Initialize data directory structure."""
        self.data_dir = Path(data_dir)
        self.raw_dir = self.data_dir / 'raw'
        self.processed_dir = self.data_dir / 'processed'

        # Create directories
        self.raw_dir.mkdir(parents=True, exist_ok=True)
        self.processed_dir.mkdir(parents=True, exist_ok=True)

        logger.info(f"Data directories created at {self.data_dir}")

    def download_data(self, tickers, start_date, end_date, interval='1d'):
        """
        Download OHLCV data from Yahoo Finance.
        Handles yfinance returning tuples or DataFrames.

        Args:
            tickers: str or list of str (e.g., 'SPY' or ['SPY', 'AAPL', 'BTC-USD'])
            start_date: str (YYYY-MM-DD)
            end_date: str (YYYY-MM-DD)
            interval: str ('1d', '1h', '15m', etc.)

        Returns:
            dict of DataFrames {ticker: df}
        """
        if isinstance(tickers, str):
            tickers = [tickers]

        data = {}

        for ticker in tickers:
            try:
                logger.info(f"Downloading {ticker}...")

                # Download with explicit parameters
                df = yf.download(
                    ticker,
                    start=start_date,
                    end=end_date,
                    interval=interval,
                    progress=False,
                    auto_adjust=False
                )

                # Handle different return types from yfinance
                if isinstance(df, tuple):
                    # Sometimes returns (data, metadata)
                    df = df[0]

                if df is None or df.empty:
                    logger.error(f"✗ No data retrieved for {ticker}")
                    continue

                # Ensure it's a DataFrame
                if not isinstance(df, pd.DataFrame):
                    logger.error(f"✗ Unexpected data type for {ticker}: {type(df)}")
                    continue

                # Handle MultiIndex columns (yfinance sometimes returns these)
                if isinstance(df.columns, pd.MultiIndex):
                    # Flatten MultiIndex - take the first level
                    df.columns = df.columns.get_level_values(0)

                # Rename columns to lowercase for consistency
                df.columns = [col.lower() for col in df.columns]

                data[ticker] = df
                logger.info(f"✓ Downloaded {ticker}: {len(df)} rows, {df.index.min().date()} to {df.index.max().date()}")

                # Save raw data
                self._save_raw_data(ticker, df)

            except Exception as e:
                logger.error(f"✗ Error downloading {ticker}: {str(e)}")
                continue

        return data

    def _save_raw_data(self, ticker, df):
        """Save raw data to CSV."""
        filepath = self.raw_dir / f"{ticker}_raw.csv"
        df.to_csv(filepath)
        logger.info(f"  → Saved raw data to {filepath}")

    def process_data(self, df, ticker, drop_missing=True):
        """
        Clean and prepare data for modeling.

        Args:
            df: Raw OHLCV DataFrame
            ticker: str (ticker symbol)
            drop_missing: bool (drop rows with missing data)

        Returns:
            Processed DataFrame
        """
        df = df.copy()

        # Remove duplicates
        df = df[~df.index.duplicated(keep='first')]

        # Sort by index
        df = df.sort_index()

        # Check for missing data
        missing_count = df.isnull().sum().sum()
        if missing_count > 0:
            logger.warning(f"  ⚠ Found {missing_count} missing values in {ticker}")
            if drop_missing:
                df = df.dropna()
                logger.info(f"  → Dropped rows with missing data")

        # Calculate returns (needed for volatility calculations)
        df['daily_return'] = df['close'].pct_change()
        df['log_return'] = np.log(df['close'] / df['close'].shift(1))

        # Check for extreme outliers (price movements > 20% in one day)
        outliers = df[df['daily_return'].abs() > 0.20]
        if len(outliers) > 0:
            logger.warning(f"  ⚠ Found {len(outliers)} potential outliers (>20% move) in {ticker}")

        logger.info(f"  → Processed {ticker}: {len(df)} rows ready")

        return df

    def calculate_realized_volatility(self, df, windows=[5, 20, 60]):
        """
        Calculate realized volatility using multiple window sizes.

        Args:
            df: DataFrame with 'log_return' column
            windows: list of int (rolling window sizes in days)

        Returns:
            DataFrame with realized_vol_* columns
        """
        df = df.copy()

        for w in windows:
            # Realized volatility = rolling standard deviation of log returns
            # Annualized by multiplying by sqrt(252) trading days
            df[f'realized_vol_{w}d'] = df['log_return'].rolling(w).std() * np.sqrt(252)

        logger.info(f"  → Calculated realized volatility for windows {windows}")
        return df

    def prepare_full_dataset(self, tickers, start_date, end_date):
        """
        Complete pipeline: download → process → add features → save.

        Args:
            tickers: list of str
            start_date: str (YYYY-MM-DD)
            end_date: str (YYYY-MM-DD)

        Returns:
            dict of processed DataFrames
        """
        logger.info(f"\n{'='*60}")
        logger.info(f"DOWNLOADING & PROCESSING DATA")
        logger.info(f"Period: {start_date} to {end_date}")
        logger.info(f"Tickers: {tickers}")
        logger.info(f"{'='*60}\n")

        # Download
        raw_data = self.download_data(tickers, start_date, end_date)

        if not raw_data:
            logger.error("No data downloaded. Exiting.")
            return {}

        # Process and add features
        processed_data = {}
        for ticker, df in raw_data.items():
            logger.info(f"\nProcessing {ticker}...")

            # Clean data
            df = self.process_data(df, ticker)

            # Add volatility measures
            df = self.calculate_realized_volatility(df)

            # Save processed data
            filepath = self.processed_dir / f"{ticker}_processed.csv"
            df.to_csv(filepath)
            logger.info(f"  → Saved processed data to {filepath}")

            processed_data[ticker] = df

        return processed_data

    def get_processed_data(self, ticker):
        """Load processed data from disk."""
        filepath = self.processed_dir / f"{ticker}_processed.csv"
        if filepath.exists():
            df = pd.read_csv(filepath, index_col=0, parse_dates=True)
            logger.info(f"Loaded {ticker} from {filepath}")
            return df
        else:
            logger.error(f"File not found: {filepath}")
            return None

    def summary(self, df, ticker):
        """Print data summary statistics."""
        logger.info(f"\n{'='*60}")
        logger.info(f"SUMMARY: {ticker}")
        logger.info(f"{'='*60}")
        logger.info(f"Date range: {df.index.min().date()} to {df.index.max().date()}")
        logger.info(f"Total rows: {len(df)}")
        logger.info(f"\nPrice (Close) Statistics:")
        logger.info(f"  Min:    ${df['close'].min():.2f}")
        logger.info(f"  Mean:   ${df['close'].mean():.2f}")
        logger.info(f"  Max:    ${df['close'].max():.2f}")
        logger.info(f"\nDaily Return Statistics:")
        logger.info(f"  Mean:   {df['daily_return'].mean()*100:.3f}%")
        logger.info(f"  Std:    {df['daily_return'].std()*100:.3f}%")
        logger.info(f"  Min:    {df['daily_return'].min()*100:.3f}%")
        logger.info(f"  Max:    {df['daily_return'].max()*100:.3f}%")
        if 'realized_vol_20d' in df.columns:
            logger.info(f"\nRealized Volatility (20d) Statistics:")
            logger.info(f"  Mean:   {df['realized_vol_20d'].mean()*100:.2f}%")
            logger.info(f"  Min:    {df['realized_vol_20d'].min()*100:.2f}%")
            logger.info(f"  Max:    {df['realized_vol_20d'].max()*100:.2f}%")


# ============================================================================
# USAGE EXAMPLE
# ============================================================================

def run_pipeline():
    """Run the data pipeline."""
    print("\n" + "="*60)
    print("STARTING DATA DOWNLOAD PIPELINE")
    print("="*60 + "\n")
    sys.stdout.flush()

    # Initialize loader
    loader = DataLoader(data_dir='data')

    # Define parameters
    tickers = ['SPY', 'AAPL', 'BTC-USD']
    end_date = datetime.now().strftime('%Y-%m-%d')
    start_date = (datetime.now() - timedelta(days=5*365)).strftime('%Y-%m-%d')

    print(f"Start date: {start_date}")
    print(f"End date: {end_date}")
    print(f"Tickers: {tickers}\n")
    sys.stdout.flush()

    # Download, process, and save
    processed_data = loader.prepare_full_dataset(tickers, start_date, end_date)

    # Print summaries
    for ticker, df in processed_data.items():
        loader.summary(df, ticker)

    print(f"\n{'='*60}")
    print("✓ Data pipeline complete!")
    print(f"Raw data saved to: {loader.raw_dir}")
    print(f"Processed data saved to: {loader.processed_dir}")
    print(f"{'='*60}\n")
    sys.stdout.flush()

    return processed_data

if __name__ == "__main__":
    run_pipeline()