# -*- coding: utf-8 -*-
"""feature_engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smpCsZSX2TeV0zfRj3WKKMIkD8txgqdY
"""

import pandas as pd
import numpy as np
from pathlib import Path
import logging

logging.basicConfig(level=logging.INFO, format='%(message)s')
logger = logging.getLogger(__name__)

class FeatureEngineer:
    """
    Create advanced volatility features from OHLCV data.
    These features will be used to train volatility models.
    """

    def __init__(self, processed_dir='data/processed'):
        self.processed_dir = Path(processed_dir)

    def load_data(self, ticker):
        """Load processed data."""
        filepath = self.processed_dir / f"{ticker}_processed.csv"
        df = pd.read_csv(filepath, index_col=0, parse_dates=True)
        return df

    def calculate_parkinson_volatility(self, df, window=20):
        """
        Parkinson volatility estimator (uses High-Low range).
        More efficient than simple std dev for capturing intraday volatility.

        Formula: sqrt(1/(4*ln(2)) * ln(H/L)^2)
        """
        df = df.copy()

        # Log high-low ratio
        hl_ratio = np.log(df['high'] / df['low'])

        # Rolling Parkinson volatility
        parkisson_vol = np.sqrt(
            (hl_ratio ** 2).rolling(window).mean() / (4 * np.log(2))
        ) * np.sqrt(252)

        df[f'parkinson_vol_{window}d'] = parkisson_vol
        return df

    def calculate_garman_klass_volatility(self, df, window=20):
        """
        Garman-Klass volatility estimator.
        More efficient than Parkinson, uses OHLC data.

        Better captures intraday volatility patterns.
        """
        df = df.copy()

        # Calculate components
        hl = np.log(df['high'] / df['low'])
        co = np.log(df['close'] / df['open'])

        # Garman-Klass formula
        gk = (0.5 * hl**2) - ((2 * np.log(2) - 1) * co**2)

        # Rolling average and annualize
        gk_vol = np.sqrt(gk.rolling(window).mean()) * np.sqrt(252)

        df[f'garman_klass_vol_{window}d'] = gk_vol
        return df

    def calculate_volatility_of_volatility(self, df, vol_col='realized_vol_20d', window=20):
        """
        Calculate volatility of volatility (vol-of-vol).
        Measures how much volatility is changing.

        High vol-of-vol = regime changes, risk of vol spikes
        """
        df = df.copy()

        if vol_col not in df.columns:
            logger.warning(f"Column {vol_col} not found")
            return df

        # Standard deviation of volatility
        vol_of_vol = df[vol_col].rolling(window).std()

        df[f'vol_of_vol_{window}d'] = vol_of_vol
        return df

    def calculate_leverage_effect(self, df, window=20):
        """
        Leverage effect: correlation between returns and volatility changes.
        Negative correlation is common (prices down → vol up).

        Useful feature for predicting vol reversions.
        """
        df = df.copy()

        # Lagged volatility change
        vol_change = df['realized_vol_20d'].pct_change()

        # Rolling correlation between returns and vol changes
        leverage = df['log_return'].rolling(window).corr(vol_change)

        df['leverage_effect'] = leverage
        return df

    def calculate_lagged_volatility_features(self, df, lags=[1, 5, 20]):
        """
        Create lagged volatility features.
        Past volatility is often the best predictor of future volatility.
        """
        df = df.copy()

        for lag in lags:
            df[f'vol_lag_{lag}d'] = df['realized_vol_20d'].shift(lag)

        return df

    def calculate_volume_features(self, df, window=20):
        """
        Volume-based features.
        Higher volume often precedes vol changes.
        """
        df = df.copy()

        # Normalize volume
        avg_volume = df['volume'].rolling(window).mean()
        df['volume_ratio'] = df['volume'] / avg_volume

        # Volume trend (increasing or decreasing)
        df['volume_trend'] = df['volume'].pct_change().rolling(window).mean()

        return df

    def calculate_price_range_features(self, df, window=20):
        """
        Intraday price range features.
        Wider ranges can indicate higher vol periods.
        """
        df = df.copy()

        # Daily range as % of close
        df['daily_range'] = (df['high'] - df['low']) / df['close']

        # Average range over window
        df['avg_range'] = df['daily_range'].rolling(window).mean()

        # Range volatility (std of ranges)
        df['range_volatility'] = df['daily_range'].rolling(window).std()

        return df

    def calculate_garch_like_features(self, df, window=20):
        """
        Features that mimic GARCH dynamics.
        Help models capture mean-reversion in volatility.
        """
        df = df.copy()

        # Squared returns (GARCH uses this)
        df['squared_return'] = df['log_return'] ** 2

        # MA of squared returns
        df['ma_squared_return'] = df['squared_return'].rolling(window).mean()

        # Deviation from mean squared return
        df['squared_return_deviation'] = df['squared_return'] - df['ma_squared_return']

        return df

    def create_all_features(self, ticker, output_suffix='_features'):
        """
        Create all volatility features and save.

        Args:
            ticker: str (ticker symbol)
            output_suffix: str (suffix for output filename)
        """
        print(f"\n{'='*60}")
        print(f"CREATING FEATURES FOR {ticker}")
        print(f"{'='*60}\n")

        # Load data
        df = self.load_data(ticker)
        print(f"Loaded {ticker}: {len(df)} rows")

        # Calculate features
        print("Calculating Parkinson volatility...")
        df = self.calculate_parkinson_volatility(df)

        print("Calculating Garman-Klass volatility...")
        df = self.calculate_garman_klass_volatility(df)

        print("Calculating volatility of volatility...")
        df = self.calculate_volatility_of_volatility(df)

        print("Calculating leverage effect...")
        df = self.calculate_leverage_effect(df)

        print("Calculating lagged volatility features...")
        df = self.calculate_lagged_volatility_features(df)

        print("Calculating volume features...")
        df = self.calculate_volume_features(df)

        print("Calculating price range features...")
        df = self.calculate_price_range_features(df)

        print("Calculating GARCH-like features...")
        df = self.calculate_garch_like_features(df)

        # Save enhanced data
        output_path = self.processed_dir / f"{ticker}{output_suffix}.csv"
        df.to_csv(output_path)
        print(f"\n✓ Saved {len(df.columns)} columns to {output_path}")

        # Print feature overview
        print(f"\nFeature columns created:")
        feature_cols = [col for col in df.columns if col not in
                       ['open', 'high', 'low', 'close', 'volume', 'daily_return', 'log_return']]
        for i, col in enumerate(feature_cols, 1):
            print(f"  {i}. {col}")

        return df

    def get_feature_summary(self, df):
        """Print summary statistics of features."""
        print(f"\n{'='*60}")
        print("FEATURE STATISTICS")
        print(f"{'='*60}\n")

        feature_cols = [col for col in df.columns if col not in
                       ['open', 'high', 'low', 'close', 'volume', 'daily_return', 'log_return']]

        for col in feature_cols:
            non_null = df[col].notna().sum()
            print(f"{col:30s}: {non_null:5d} non-null, mean={df[col].mean():8.4f}, std={df[col].std():8.4f}")


# ============================================================================
# USAGE EXAMPLE
# ============================================================================

if __name__ == "__main__":

    engineer = FeatureEngineer(processed_dir='data/processed')

    tickers = ['SPY', 'AAPL', 'BTC-USD']

    print("\n" + "="*60)
    print("FEATURE ENGINEERING PIPELINE")
    print("="*60)

    for ticker in tickers:
        df = engineer.create_all_features(ticker)
        engineer.get_feature_summary(df)

    print(f"\n{'='*60}")
    print("✓ Feature engineering complete!")
    print(f"{'='*60}\n")