# -*- coding: utf-8 -*-
"""backtester

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smpCsZSX2TeV0zfRj3WKKMIkD8txgqdY
"""

import pandas as pd
import numpy as np
from pathlib import Path
from typing import Tuple, Dict, List
import warnings

warnings.filterwarnings('ignore')


class WalkForwardValidator:
    """
    Implements walk-forward validation for time series forecasting.

    Walk-forward validation prevents look-ahead bias by training on historical
    data and testing on future data in sequential windows. This methodology
    ensures models are evaluated on truly out-of-sample predictions, critical
    for financial forecasting applications.

    Architecture:
        Train [0:t1] -> Validate [t1:t2] -> Test [t2:end]
        Prevents future information leakage into model training.
    """

    def __init__(self, data_dir='data/processed', train_ratio=0.6, val_ratio=0.2):
        """
        Initialize walk-forward validator.

        Args:
            data_dir: Path to processed data directory
            train_ratio: Fraction of data for training (default 0.6)
            val_ratio: Fraction of data for validation (default 0.2)
                       Remaining fraction automatically becomes test set
        """
        self.data_dir = Path(data_dir)
        self.train_ratio = train_ratio
        self.val_ratio = val_ratio
        self.test_ratio = 1.0 - train_ratio - val_ratio

        self._validate_ratios()

    def _validate_ratios(self):
        """Validate that ratios sum to 1.0 and are positive."""
        total = self.train_ratio + self.val_ratio + self.test_ratio

        if not np.isclose(total, 1.0):
            raise ValueError(
                f"Ratios must sum to 1.0, got {total:.2f} "
                f"(train={self.train_ratio}, val={self.val_ratio}, test={self.test_ratio})"
            )

        if any(r <= 0 for r in [self.train_ratio, self.val_ratio, self.test_ratio]):
            raise ValueError("All ratios must be positive")

    def split_series(self, df: pd.DataFrame) -> Dict[str, pd.DataFrame]:
        """
        Split time series into train/val/test sets maintaining chronological order.

        Critical for preventing look-ahead bias: training always precedes validation
        which precedes testing. No shuffling or reordering of indices.

        Args:
            df: Input DataFrame with DatetimeIndex

        Returns:
            Dictionary with 'train', 'val', 'test' DataFrames

        Raises:
            ValueError: If DataFrame is empty or has insufficient rows
        """
        if df is None or len(df) == 0:
            raise ValueError("DataFrame is empty")

        n = len(df)
        train_end = int(n * self.train_ratio)
        val_end = train_end + int(n * self.val_ratio)

        if train_end < 50:
            raise ValueError(f"Training set too small ({train_end} rows, need >= 50)")
        if (val_end - train_end) < 20:
            raise ValueError(f"Validation set too small ({val_end - train_end} rows, need >= 20)")
        if (n - val_end) < 20:
            raise ValueError(f"Test set too small ({n - val_end} rows, need >= 20)")

        splits = {
            'train': df.iloc[:train_end],
            'val': df.iloc[train_end:val_end],
            'test': df.iloc[val_end:]
        }

        return splits

    def rolling_window_split(self, df: pd.DataFrame, window_size: int,
                            step_size: int = None) -> List[Tuple[pd.DataFrame, pd.DataFrame]]:
        """
        Generate rolling window splits for expanding window validation.

        Use case: Expanding window where training set grows with each iteration,
        validating model performance as more historical data becomes available.

        Args:
            df: Input DataFrame
            window_size: Size of rolling validation window
            step_size: Steps to advance window (default: window_size)

        Yields:
            Tuples of (training_df, validation_df)
        """
        if step_size is None:
            step_size = window_size

        if window_size <= 0 or step_size <= 0:
            raise ValueError("Window and step sizes must be positive")

        train_start = 0
        val_start = len(df) - window_size

        splits = []
        while val_start > 0:
            train_df = df.iloc[train_start:val_start]
            val_df = df.iloc[val_start:val_start + window_size]

            if len(train_df) > 0 and len(val_df) > 0:
                splits.append((train_df, val_df))

            val_start -= step_size

        return splits[::-1]  # Reverse to chronological order

    def expanding_window_split(self, df: pd.DataFrame,
                              min_train_size: int = 100,
                              step_size: int = 20) -> List[Tuple[pd.DataFrame, pd.DataFrame]]:
        """
        Generate expanding window splits for online learning validation.

        Training set grows monotonically; validation set is constant size.
        Models are evaluated as if learning continuously from new data.

        Args:
            df: Input DataFrame
            min_train_size: Minimum training samples to start
            step_size: How many rows to add to training set each iteration

        Yields:
            Tuples of (expanding_training_df, validation_df)
        """
        if min_train_size <= 0 or step_size <= 0:
            raise ValueError("Sizes must be positive")

        if min_train_size >= len(df):
            raise ValueError(f"Min train size {min_train_size} >= data length {len(df)}")

        splits = []
        train_end = min_train_size

        while train_end < len(df) - 1:
            train_df = df.iloc[:train_end]
            val_df = df.iloc[train_end:train_end + 1]

            splits.append((train_df, val_df))
            train_end += step_size

        return splits

    def purged_walk_forward_split(self, df: pd.DataFrame,
                                 purge_pct: float = 0.01) -> Dict[str, pd.DataFrame]:
        """
        Generate purged walk-forward splits accounting for data leakage.

        Advanced methodology: Removes data between test and next training set
        to account for information leakage through overlapping features.
        Particularly important for models with lagged features or rolling statistics.

        Args:
            df: Input DataFrame
            purge_pct: Fraction of data to purge between test/train (default 1%)

        Returns:
            Dictionary with purged 'train', 'val', 'test' splits
        """
        n = len(df)
        train_end = int(n * self.train_ratio)
        val_end = train_end + int(n * self.val_ratio)

        purge_size = int(n * purge_pct)

        splits = {
            'train': df.iloc[:train_end - purge_size],
            'val': df.iloc[train_end:val_end - purge_size],
            'test': df.iloc[val_end:]
        }

        return splits

    def get_training_info(self, df: pd.DataFrame) -> Dict:
        """
        Return detailed information about proposed data splits.

        Useful for auditing: confirms no look-ahead bias, dates non-overlapping.

        Args:
            df: Input DataFrame

        Returns:
            Dictionary with split sizes, dates, and validation status
        """
        splits = self.split_series(df)

        info = {
            'total_samples': len(df),
            'train': {
                'samples': len(splits['train']),
                'start_date': splits['train'].index.min(),
                'end_date': splits['train'].index.max(),
                'pct': len(splits['train']) / len(df) * 100
            },
            'val': {
                'samples': len(splits['val']),
                'start_date': splits['val'].index.min(),
                'end_date': splits['val'].index.max(),
                'pct': len(splits['val']) / len(df) * 100
            },
            'test': {
                'samples': len(splits['test']),
                'start_date': splits['test'].index.min(),
                'end_date': splits['test'].index.max(),
                'pct': len(splits['test']) / len(df) * 100
            },
            'chronological_order': (
                splits['train'].index.max() < splits['val'].index.min() and
                splits['val'].index.max() < splits['test'].index.min()
            ),
            'no_overlap': (
                splits['train'].index.max() < splits['val'].index.min() and
                splits['val'].index.max() < splits['test'].index.min()
            )
        }

        return info

    def print_split_info(self, ticker: str, df: pd.DataFrame):
        """
        Pretty-print data split information for auditing.

        Args:
            ticker: Asset symbol
            df: Input DataFrame
        """
        info = self.get_training_info(df)

        print(f"\n{ticker} Walk-Forward Split:")
        print("-" * 70)
        print(f"Total samples: {info['total_samples']}")
        print(f"\nTrain: {info['train']['samples']:4d} ({info['train']['pct']:5.1f}%) " +
              f"[{info['train']['start_date'].date()} → {info['train']['end_date'].date()}]")
        print(f"Val:   {info['val']['samples']:4d} ({info['val']['pct']:5.1f}%) " +
              f"[{info['val']['start_date'].date()} → {info['val']['end_date'].date()}]")
        print(f"Test:  {info['test']['samples']:4d} ({info['test']['pct']:5.1f}%) " +
              f"[{info['test']['start_date'].date()} → {info['test']['end_date'].date()}]")
        print(f"\nNo look-ahead bias: {info['no_overlap']}")
        print(f"Chronological order: {info['chronological_order']}")


class BacktestMetrics:
    """Calculate and report backtest performance metrics."""

    @staticmethod
    def calculate_sharpe_ratio(returns: np.ndarray, risk_free_rate: float = 0.02) -> float:
        """
        Calculate Sharpe ratio of forecast-based strategy.

        Args:
            returns: Array of strategy returns
            risk_free_rate: Annual risk-free rate (default 2%)

        Returns:
            Annualized Sharpe ratio
        """
        excess_returns = returns - risk_free_rate / 252

        if np.std(excess_returns) == 0:
            return 0.0

        return np.mean(excess_returns) / np.std(excess_returns) * np.sqrt(252)

    @staticmethod
    def calculate_max_drawdown(returns: np.ndarray) -> float:
        """
        Calculate maximum drawdown of cumulative returns.

        Args:
            returns: Array of returns

        Returns:
            Maximum drawdown as decimal (e.g., -0.15 for -15%)
        """
        cumulative = np.cumprod(1 + returns)
        running_max = np.maximum.accumulate(cumulative)
        drawdown = (cumulative - running_max) / running_max

        return np.min(drawdown)

    @staticmethod
    def calculate_hit_rate(actual: np.ndarray, forecast: np.ndarray) -> float:
        """
        Calculate directional accuracy percentage.

        Args:
            actual: Array of actual values
            forecast: Array of predicted values

        Returns:
            Hit rate as percentage (0-100)
        """
        if len(actual) < 2:
            return 0.0

        actual_direction = np.diff(actual) > 0
        forecast_direction = np.diff(forecast) > 0
        hit_rate = np.mean(actual_direction == forecast_direction)

        return hit_rate * 100