# -*- coding: utf-8 -*-
"""evaluator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smpCsZSX2TeV0zfRj3WKKMIkD8txgqdY
"""

import pandas as pd
import numpy as np
from pathlib import Path
from typing import Dict, List, Tuple
from sklearn.metrics import mean_absolute_error, mean_squared_error, mean_absolute_percentage_error
import warnings

warnings.filterwarnings('ignore')


class ModelEvaluator:
    """
    Comprehensive model evaluation and comparison engine.

    Standardizes metric computation across all forecasting models, enabling
    fair comparison of volatility and price predictions. Computes statistical
    measures of forecast accuracy and provides diagnostic outputs for model selection.
    """

    def __init__(self, results_dir='results'):
        """
        Initialize evaluator.

        Args:
            results_dir: Directory containing forecast CSV files
        """
        self.results_dir = Path(results_dir)
        self.evaluation_results = {}

    def evaluate_forecast(self, actual: np.ndarray, forecast: np.ndarray,
                         name: str = "") -> Dict:
        """
        Compute comprehensive evaluation metrics for single model.

        Args:
            actual: Array of actual values
            forecast: Array of predicted values
            name: Optional string for logging

        Returns:
            Dictionary with MAE, RMSE, MAPE, R², correlation, directional accuracy

        Raises:
            ValueError: If arrays have different lengths or insufficient data
        """
        if len(actual) != len(forecast):
            raise ValueError(f"Length mismatch: actual={len(actual)}, forecast={len(forecast)}")

        if len(actual) < 2:
            raise ValueError(f"Insufficient samples: {len(actual)}, need >= 2")

        # Remove NaN values
        mask = ~(np.isnan(actual) | np.isnan(forecast))
        actual_clean = actual[mask]
        forecast_clean = forecast[mask]

        if len(actual_clean) < 2:
            return None

        # Mean Absolute Error
        mae = mean_absolute_error(actual_clean, forecast_clean)

        # Root Mean Squared Error
        rmse = np.sqrt(mean_squared_error(actual_clean, forecast_clean))

        # Mean Absolute Percentage Error
        mape = mean_absolute_percentage_error(actual_clean, forecast_clean)

        # Mean Squared Error
        mse = mean_squared_error(actual_clean, forecast_clean)

        # R-squared (coefficient of determination)
        ss_res = np.sum((actual_clean - forecast_clean) ** 2)
        ss_tot = np.sum((actual_clean - np.mean(actual_clean)) ** 2)
        r_squared = 1 - (ss_res / ss_tot) if ss_tot != 0 else 0.0

        # Pearson Correlation
        try:
            correlation = np.corrcoef(actual_clean, forecast_clean)[0, 1]
        except:
            correlation = 0.0

        # Directional Accuracy
        actual_direction = np.diff(actual_clean) > 0
        forecast_direction = np.diff(forecast_clean) > 0
        directional_accuracy = np.mean(actual_direction == forecast_direction)

        # Mean Directional Accuracy (unsigned)
        mda = np.mean(np.abs(actual_direction.astype(int) - forecast_direction.astype(int))) / 2

        # Theil's U statistic (relative to naive forecast)
        naive_forecast = actual_clean[:-1]
        numerator = np.sum((forecast_clean[1:] - actual_clean[1:]) ** 2)
        denominator = np.sum((naive_forecast - actual_clean[1:]) ** 2)
        theils_u = np.sqrt(numerator / denominator) if denominator > 0 else np.inf

        metrics = {
            'MAE': mae,
            'RMSE': rmse,
            'MAPE': mape,
            'MSE': mse,
            'R_squared': r_squared,
            'Correlation': correlation,
            'Directional_Accuracy': directional_accuracy,
            'Mean_Directional_Accuracy': mda,
            'Theils_U': theils_u,
            'N_samples': len(actual_clean)
        }

        return metrics

    def compare_models(self, ticker: str, model_names: List[str],
                      forecast_suffix: str = "_forecast.csv") -> pd.DataFrame:
        """
        Compare multiple models on same asset.

        Args:
            ticker: Asset symbol (SPY, AAPL, BTC-USD)
            model_names: List of model names to compare
            forecast_suffix: Expected forecast filename pattern

        Returns:
            DataFrame with metrics for each model
        """
        results = []

        for model_name in model_names:
            filepath = self.results_dir / f"{ticker}_{model_name}{forecast_suffix}"

            if not filepath.exists():
                continue

            try:
                df = pd.read_csv(filepath, index_col=0, parse_dates=True)
                df = df.dropna()

                if len(df) == 0:
                    continue

                actual = df['test_actual'].values
                forecast = df['test_forecast'].values

                metrics = self.evaluate_forecast(actual, forecast, name=model_name)

                if metrics:
                    metrics['Model'] = model_name
                    metrics['Ticker'] = ticker
                    results.append(metrics)

            except Exception as e:
                continue

        return pd.DataFrame(results)

    def rank_models(self, comparison_df: pd.DataFrame, metric: str = 'Correlation',
                   ascending: bool = False) -> pd.DataFrame:
        """
        Rank models by specified metric.

        Args:
            comparison_df: DataFrame from compare_models()
            metric: Metric to rank by (MAE, Correlation, etc.)
            ascending: Sort ascending if True, descending if False

        Returns:
            DataFrame sorted by metric with rank column
        """
        if metric not in comparison_df.columns:
            raise ValueError(f"Metric '{metric}' not found. Available: {comparison_df.columns.tolist()}")

        ranked = comparison_df.sort_values(metric, ascending=ascending).reset_index(drop=True)
        ranked['Rank'] = range(1, len(ranked) + 1)

        return ranked[['Rank', 'Model', 'Ticker', metric]]

    def best_model(self, comparison_df: pd.DataFrame, metric: str = 'Correlation') -> str:
        """
        Identify best performing model by metric.

        Args:
            comparison_df: DataFrame from compare_models()
            metric: Metric to optimize

        Returns:
            Name of best model
        """
        if metric not in comparison_df.columns:
            raise ValueError(f"Metric '{metric}' not found")

        if metric in ['MAE', 'RMSE', 'MAPE', 'MSE', 'Theils_U']:
            best_idx = comparison_df[metric].idxmin()
        else:  # Higher is better for R², Correlation, Accuracy
            best_idx = comparison_df[metric].idxmax()

        return comparison_df.loc[best_idx, 'Model']

    def ensemble_predictions(self, ticker: str, model_names: List[str],
                            weights: Dict[str, float] = None) -> Tuple[np.ndarray, np.ndarray]:
        """
        Generate weighted ensemble predictions from multiple models.

        Args:
            ticker: Asset symbol
            model_names: List of model names to ensemble
            weights: Dictionary {model_name: weight}. If None, equal weights.

        Returns:
            Tuple of (actual_values, ensemble_forecast)
        """
        if weights is None:
            weights = {m: 1.0 / len(model_names) for m in model_names}

        # Normalize weights
        total_weight = sum(weights.values())
        weights = {k: v / total_weight for k, v in weights.items()}

        ensemble_forecast = None
        actual = None

        for model_name in model_names:
            if model_name not in weights:
                continue

            filepath = self.results_dir / f"{ticker}_{model_name}_forecast.csv"

            if not filepath.exists():
                continue

            df = pd.read_csv(filepath, index_col=0, parse_dates=True).dropna()

            if actual is None:
                actual = df['test_actual'].values
                ensemble_forecast = weights[model_name] * df['test_forecast'].values
            else:
                # Align to common indices
                ensemble_forecast += weights[model_name] * df['test_forecast'].values

        if ensemble_forecast is None:
            raise ValueError(f"No valid forecasts found for {ticker}")

        return actual, ensemble_forecast

    def volatility_vs_price_comparison(self, ticker: str) -> pd.DataFrame:
        """
        Compare volatility and price forecasting performance on same asset.

        Args:
            ticker: Asset symbol

        Returns:
            DataFrame comparing volatility vs price models
        """
        volatility_models = ['garch', 'ewma', 'xgboost', 'lightgbm']
        price_models = ['arima', 'prophet', 'lstm', 'ensemble']

        vol_comparison = self.compare_models(ticker, volatility_models)
        price_comparison = self.compare_models(ticker, price_models)

        vol_comparison['Type'] = 'Volatility'
        price_comparison['Type'] = 'Price'

        combined = pd.concat([vol_comparison, price_comparison], ignore_index=True)

        return combined.sort_values('Correlation', ascending=False)

    def print_evaluation_report(self, ticker: str, metrics: Dict):
        """
        Pretty-print comprehensive evaluation report.

        Args:
            ticker: Asset symbol
            metrics: Dictionary from evaluate_forecast()
        """
        if metrics is None:
            print(f"{ticker}: No valid metrics")
            return

        print(f"\n{ticker} Evaluation Report:")
        print("-" * 70)
        print(f"Samples:                {metrics['N_samples']:6d}")
        print(f"Mean Absolute Error:    {metrics['MAE']:10.4f}")
        print(f"Root Mean Squared Error:{metrics['RMSE']:10.4f}")
        print(f"Mean Absolute % Error:  {metrics['MAPE']*100:9.2f}%")
        print(f"R-squared:              {metrics['R_squared']:10.4f}")
        print(f"Correlation:            {metrics['Correlation']:10.4f}")
        print(f"Directional Accuracy:   {metrics['Directional_Accuracy']*100:9.2f}%")
        print(f"Theil's U:              {metrics['Theils_U']:10.4f}")

    def correlation_matrix(self, ticker: str, model_names: List[str]) -> pd.DataFrame:
        """
        Compute correlation matrix of predictions across models.

        Identifies models that make similar vs different predictions,
        useful for ensemble diversification.

        Args:
            ticker: Asset symbol
            model_names: List of model names

        Returns:
            Correlation matrix of predictions
        """
        predictions = {}

        for model_name in model_names:
            filepath = self.results_dir / f"{ticker}_{model_name}_forecast.csv"

            if filepath.exists():
                df = pd.read_csv(filepath, index_col=0, parse_dates=True).dropna()
                predictions[model_name] = df['test_forecast'].values

        if not predictions:
            raise ValueError(f"No forecasts found for {ticker}")

        df_predictions = pd.DataFrame(predictions)
        return df_predictions.corr()