# -*- coding: utf-8 -*-
"""utils

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smpCsZSX2TeV0zfRj3WKKMIkD8txgqdY
"""

import pandas as pd
import numpy as np
from pathlib import Path
from typing import List, Tuple, Dict
import warnings

warnings.filterwarnings('ignore')


class DataUtilities:
    """Utilities for data loading, validation, and preprocessing."""

    @staticmethod
    def load_processed_data(ticker: str, data_dir: str = 'data/processed') -> pd.DataFrame:
        """
        Load processed data for asset.

        Args:
            ticker: Asset symbol
            data_dir: Directory containing processed data

        Returns:
            DataFrame with OHLCV and features

        Raises:
            FileNotFoundError: If data file not found
        """
        filepath = Path(data_dir) / f"{ticker}_processed.csv"

        if not filepath.exists():
            raise FileNotFoundError(f"Data not found: {filepath}")

        df = pd.read_csv(filepath, index_col=0, parse_dates=True)
        return df

    @staticmethod
    def load_features_data(ticker: str, data_dir: str = 'data/processed') -> pd.DataFrame:
        """
        Load data with engineered features.

        Args:
            ticker: Asset symbol
            data_dir: Directory containing processed data

        Returns:
            DataFrame with features
        """
        filepath = Path(data_dir) / f"{ticker}_features.csv"

        if not filepath.exists():
            filepath = Path(data_dir) / f"{ticker}_processed.csv"

        df = pd.read_csv(filepath, index_col=0, parse_dates=True)
        return df

    @staticmethod
    def validate_dataframe(df: pd.DataFrame, min_rows: int = 100) -> Tuple[bool, str]:
        """
        Validate DataFrame for modeling.

        Args:
            df: DataFrame to validate
            min_rows: Minimum required rows

        Returns:
            Tuple of (is_valid, error_message)
        """
        if df is None:
            return False, "DataFrame is None"

        if len(df) < min_rows:
            return False, f"Insufficient rows: {len(df)} < {min_rows}"

        if not isinstance(df.index, pd.DatetimeIndex):
            return False, "Index is not DatetimeIndex"

        if df.isnull().all().any():
            null_cols = df.columns[df.isnull().all()].tolist()
            return False, f"Columns with all nulls: {null_cols}"

        return True, "Valid"

    @staticmethod
    def get_available_tickers(data_dir: str = 'data/processed') -> List[str]:
        """
        List available assets in data directory.

        Args:
            data_dir: Directory containing data files

        Returns:
            List of ticker symbols
        """
        data_path = Path(data_dir)

        if not data_path.exists():
            return []

        # Find processed files
        files = list(data_path.glob('*_processed.csv'))
        tickers = [f.stem.replace('_processed', '') for f in files]

        return sorted(set(tickers))

    @staticmethod
    def date_range_summary(df: pd.DataFrame) -> Dict:
        """
        Summarize date range of DataFrame.

        Args:
            df: Input DataFrame with DatetimeIndex

        Returns:
            Dictionary with date statistics
        """
        return {
            'start_date': df.index.min(),
            'end_date': df.index.max(),
            'duration_days': (df.index.max() - df.index.min()).days,
            'duration_years': (df.index.max() - df.index.min()).days / 365.25,
            'total_rows': len(df),
            'trading_days': len(df),
            'gaps': len(df) - (df.index.max() - df.index.min()).days
        }


class ForecastUtilities:
    """Utilities for loading and manipulating forecast results."""

    @staticmethod
    def load_forecast(ticker: str, model_name: str,
                     results_dir: str = 'results') -> pd.DataFrame:
        """
        Load forecast results for asset and model.

        Args:
            ticker: Asset symbol
            model_name: Name of forecasting model
            results_dir: Directory containing results

        Returns:
            DataFrame with test_actual and test_forecast columns

        Raises:
            FileNotFoundError: If forecast file not found
        """
        filepath = Path(results_dir) / f"{ticker}_{model_name}_forecast.csv"

        if not filepath.exists():
            raise FileNotFoundError(f"Forecast not found: {filepath}")

        df = pd.read_csv(filepath, index_col=0, parse_dates=True)
        return df.dropna()

    @staticmethod
    def get_available_forecasts(ticker: str = None,
                               results_dir: str = 'results') -> Dict[str, List[str]]:
        """
        List available forecasts by ticker and model.

        Args:
            ticker: Optional ticker to filter
            results_dir: Directory containing results

        Returns:
            Dictionary {ticker: [model_names]}
        """
        results_path = Path(results_dir)

        if not results_path.exists():
            return {}

        forecasts = {}

        for file in results_path.glob('*_forecast.csv'):
            parts = file.stem.split('_')

            # Handle multi-part tickers like BTC-USD
            if len(parts) >= 3 and parts[-1] == 'forecast':
                model = '_'.join(parts[:-2])
                tick = parts[-3]
            else:
                continue

            if ticker and tick != ticker:
                continue

            if tick not in forecasts:
                forecasts[tick] = []
            forecasts[tick].append(model)

        return {k: sorted(v) for k, v in sorted(forecasts.items())}

    @staticmethod
    def align_forecasts(ticker: str, model_names: List[str],
                       results_dir: str = 'results') -> Tuple[np.ndarray, Dict[str, np.ndarray]]:
        """
        Load and align forecasts from multiple models on common dates.

        Args:
            ticker: Asset symbol
            model_names: List of model names
            results_dir: Directory containing results

        Returns:
            Tuple of (actual_values, {model_name: forecast_values})
        """
        forecasts_dict = {}
        common_idx = None

        for model_name in model_names:
            try:
                df = ForecastUtilities.load_forecast(ticker, model_name, results_dir)

                if common_idx is None:
                    common_idx = df.index
                else:
                    common_idx = common_idx.intersection(df.index)

                forecasts_dict[model_name] = df
            except FileNotFoundError:
                continue

        if not forecasts_dict:
            raise ValueError(f"No forecasts found for {ticker}")

        # Align all to common index
        actual = forecasts_dict[list(forecasts_dict.keys())[0]].loc[common_idx, 'test_actual'].values
        aligned_forecasts = {
            k: df.loc[common_idx, 'test_forecast'].values
            for k, df in forecasts_dict.items()
        }

        return actual, aligned_forecasts


class MetricsUtilities:
    """Utilities for metric computation and comparison."""

    @staticmethod
    def relative_improvement(baseline: float, current: float,
                           metric: str = 'MAE') -> float:
        """
        Calculate relative improvement from baseline to current.

        Args:
            baseline: Baseline metric value
            current: Current metric value
            metric: Type of metric (MAE, Correlation, etc.)

        Returns:
            Percentage improvement (positive = better)
        """
        if baseline == 0:
            return 0.0

        # For metrics where lower is better (MAE, RMSE, MAPE)
        if metric in ['MAE', 'RMSE', 'MAPE', 'MSE', 'Theils_U']:
            improvement = (baseline - current) / baseline * 100
        else:  # For metrics where higher is better
            improvement = (current - baseline) / baseline * 100

        return improvement

    @staticmethod
    def metric_comparison_table(metrics_list: List[Dict],
                               sort_by: str = 'Correlation') -> pd.DataFrame:
        """
        Create comparison table from metrics dictionaries.

        Args:
            metrics_list: List of metrics dictionaries
            sort_by: Metric to sort by

        Returns:
            Formatted comparison DataFrame
        """
        df = pd.DataFrame(metrics_list)

        if sort_by in df.columns:
            # Determine sort order
            ascending = sort_by in ['MAE', 'RMSE', 'MAPE', 'MSE', 'Theils_U']
            df = df.sort_values(sort_by, ascending=ascending)

        return df

    @staticmethod
    def format_metrics_for_display(metrics: Dict, decimal_places: int = 4) -> Dict:
        """
        Format metrics for nice display.

        Args:
            metrics: Dictionary of metrics
            decimal_places: Number of decimal places

        Returns:
            Dictionary with formatted strings
        """
        formatted = {}

        for key, value in metrics.items():
            if isinstance(value, float):
                if key in ['MAPE', 'Directional_Accuracy', 'Mean_Directional_Accuracy']:
                    formatted[key] = f"{value*100:.{decimal_places-2}f}%"
                else:
                    formatted[key] = f"{value:.{decimal_places}f}"
            else:
                formatted[key] = str(value)

        return formatted


class VisualizationUtilities:
    """Utilities for preparing data for visualization."""

    @staticmethod
    def prepare_forecast_plot_data(actual: np.ndarray, forecast: np.ndarray,
                                  dates: pd.DatetimeIndex = None) -> pd.DataFrame:
        """
        Prepare forecast data for time series plotting.

        Args:
            actual: Array of actual values
            forecast: Array of predicted values
            dates: Optional datetime index

        Returns:
            DataFrame with aligned actual/forecast and dates
        """
        if dates is None:
            dates = pd.date_range(start='2024-01-01', periods=len(actual), freq='D')

        return pd.DataFrame({
            'date': dates,
            'actual': actual,
            'forecast': forecast
        })

    @staticmethod
    def prepare_residuals(actual: np.ndarray, forecast: np.ndarray,
                         dates: pd.DatetimeIndex = None) -> pd.DataFrame:
        """
        Prepare residuals (errors) for analysis.

        Args:
            actual: Array of actual values
            forecast: Array of predicted values
            dates: Optional datetime index

        Returns:
            DataFrame with residuals and statistics
        """
        residuals = actual - forecast

        if dates is None:
            dates = pd.date_range(start='2024-01-01', periods=len(actual), freq='D')

        return pd.DataFrame({
            'date': dates,
            'actual': actual,
            'forecast': forecast,
            'residual': residuals,
            'abs_error': np.abs(residuals),
            'pct_error': np.abs(residuals) / np.abs(actual)
        })

    @staticmethod
    def get_color_by_metric(value: float, metric: str = 'Correlation',
                           thresholds: Dict = None) -> str:
        """
        Get color for metric visualization (red/orange/green).

        Args:
            value: Metric value
            metric: Type of metric
            thresholds: Custom threshold dictionary

        Returns:
            Color code (red, orange, green)
        """
        if thresholds is None:
            if metric in ['MAE', 'RMSE', 'MAPE', 'MSE']:
                # Lower is better
                thresholds = {'good': 0.05, 'ok': 0.10}  # Example
            else:  # Correlation, Accuracy
                # Higher is better
                thresholds = {'good': 0.80, 'ok': 0.50}

        if metric in ['MAE', 'RMSE', 'MAPE', 'MSE']:
            if value < thresholds.get('good', 0.05):
                return 'green'
            elif value < thresholds.get('ok', 0.10):
                return 'orange'
            else:
                return 'red'
        else:
            if value > thresholds.get('good', 0.80):
                return 'green'
            elif value > thresholds.get('ok', 0.50):
                return 'orange'
            else:
                return 'red'


class ConfigUtilities:
    """Configuration and constants management."""

    VOLATILITY_MODELS = ['garch', 'ewma', 'xgboost', 'lightgbm']
    PRICE_MODELS = ['arima', 'prophet', 'lstm', 'ensemble']
    ALL_MODELS = VOLATILITY_MODELS + PRICE_MODELS

    TICKERS = ['SPY', 'AAPL', 'BTC-USD']

    MODEL_DESCRIPTIONS = {
        'garch': 'GARCH(1,1) - Conditional heteroscedasticity',
        'ewma': 'Exponential Weighted Moving Average (λ=0.94)',
        'xgboost': 'XGBoost - Gradient boosting on features',
        'lightgbm': 'LightGBM - Light gradient boosting',
        'arima': 'ARIMA(3,1,1) - Autoregressive integrated MA',
        'prophet': 'Prophet - Trend decomposition',
        'lstm': 'LSTM - Deep recurrent neural network',
        'ensemble': 'Ensemble - Weighted average of price models'
    }

    @staticmethod
    def get_model_type(model_name: str) -> str:
        """
        Get model type (volatility or price).

        Args:
            model_name: Name of model

        Returns:
            'volatility' or 'price'
        """
        if model_name in ConfigUtilities.VOLATILITY_MODELS:
            return 'volatility'
        elif model_name in ConfigUtilities.PRICE_MODELS:
            return 'price'
        else:
            return 'unknown'

    @staticmethod
    def get_model_description(model_name: str) -> str:
        """
        Get description of model.

        Args:
            model_name: Name of model

        Returns:
            Model description string
        """
        return ConfigUtilities.MODEL_DESCRIPTIONS.get(model_name, 'Unknown model')