# -*- coding: utf-8 -*-
"""base_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smpCsZSX2TeV0zfRj3WKKMIkD8txgqdY
"""

from abc import ABC, abstractmethod
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.metrics import mean_absolute_error, mean_squared_error
import warnings

warnings.filterwarnings('ignore')


class BaseModel(ABC):
    """
    Abstract base class for all forecasting models.

    Defines consistent interface for data loading, model training,
    evaluation, and result persistence. Ensures reproducibility and
    standardized metrics across different model implementations.
    """

    def __init__(self, data_dir='data/processed', output_dir='results'):
        """
        Initialize base model with directory configuration.

        Args:
            data_dir: Path to processed data directory
            output_dir: Path to save forecast results
        """
        self.data_dir = Path(data_dir)
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)

        self.results = {}
        self.model = None

    @abstractmethod
    def train_and_evaluate(self, ticker):
        """
        Train model on asset and evaluate on test set.
        Must be implemented by subclasses.

        Args:
            ticker: Asset symbol (SPY, AAPL, BTC-USD)
        """
        pass

    @abstractmethod
    def load_data(self, ticker):
        """
        Load processed data for specified asset.
        Must be implemented by subclasses based on data requirements.

        Args:
            ticker: Asset symbol

        Returns:
            DataFrame with OHLCV and computed features
        """
        pass

    def split_data(self, df, train_ratio=0.6, val_ratio=0.2):
        """
        Split time series data respecting chronological order.

        Walk-forward methodology: training precedes validation which
        precedes testing. No look-ahead bias by construction.

        Args:
            df: Full time series DataFrame
            train_ratio: Fraction for training (default 0.6)
            val_ratio: Fraction for validation (default 0.2)

        Returns:
            Dictionary with 'train', 'val', 'test' DataFrames
        """
        n = len(df)
        train_end = int(n * train_ratio)
        val_end = train_end + int(n * val_ratio)

        splits = {
            'train': df.iloc[:train_end],
            'val': df.iloc[train_end:val_end],
            'test': df.iloc[val_end:]
        }

        return splits

    def calculate_metrics(self, actual, forecast, name=""):
        """
        Compute comprehensive evaluation metrics.

        Args:
            actual: Array of actual values
            forecast: Array of predicted values
            name: String prefix for logging (optional)

        Returns:
            Dictionary with MAE, RMSE, MAPE, correlation, directional accuracy
        """
        # Remove NaN values
        mask = ~(np.isnan(actual) | np.isnan(forecast))
        actual_clean = np.array(actual)[mask]
        forecast_clean = np.array(forecast)[mask]

        if len(actual_clean) == 0:
            return None

        # Mean Absolute Error
        mae = mean_absolute_error(actual_clean, forecast_clean)

        # Root Mean Squared Error
        rmse = np.sqrt(mean_squared_error(actual_clean, forecast_clean))

        # Mean Absolute Percentage Error
        mape = np.mean(np.abs((actual_clean - forecast_clean) / actual_clean))

        # Correlation
        try:
            correlation = np.corrcoef(actual_clean, forecast_clean)[0, 1]
        except:
            correlation = 0.0

        # Directional Accuracy
        if len(actual_clean) > 1:
            actual_direction = np.diff(actual_clean) > 0
            forecast_direction = np.diff(forecast_clean) > 0
            directional_accuracy = np.mean(actual_direction == forecast_direction)
        else:
            directional_accuracy = 0.0

        metrics = {
            'MAE': mae,
            'RMSE': rmse,
            'MAPE': mape,
            'Correlation': correlation,
            'Directional_Accuracy': directional_accuracy,
            'N_samples': len(actual_clean)
        }

        return metrics

    def save_forecast(self, ticker, actual, forecast, index=None):
        """
        Save forecast results to CSV with timestamps.

        Args:
            ticker: Asset symbol
            actual: Array of actual values
            forecast: Array of predicted values
            index: DatetimeIndex for alignment (optional)
        """
        if index is None:
            index = range(len(actual))

        forecast_df = pd.DataFrame({
            'test_actual': actual,
            'test_forecast': forecast
        }, index=index)

        model_name = self.__class__.__name__.lower()
        filepath = self.output_dir / f"{ticker}_{model_name}_forecast.csv"
        forecast_df.to_csv(filepath)

        return filepath

    def log_metrics(self, ticker, metrics):
        """
        Log evaluation metrics to console in standardized format.

        Args:
            ticker: Asset symbol
            metrics: Dictionary from calculate_metrics()
        """
        if metrics is None:
            print(f"  {ticker}: No valid metrics")
            return

        print(f"  {ticker:10s} - MAE={metrics['MAE']:.4f}  " +
              f"RMSE={metrics['RMSE']:.4f}  " +
              f"Corr={metrics['Correlation']:.4f}  " +
              f"Dir%={metrics['Directional_Accuracy']*100:5.1f}%")

    def validate_data(self, df, min_samples=50):
        """
        Validate dataset before model training.

        Args:
            df: Input DataFrame
            min_samples: Minimum required rows

        Returns:
            Tuple (is_valid, error_message)
        """
        if df is None:
            return False, "DataFrame is None"

        if len(df) < min_samples:
            return False, f"Insufficient data ({len(df)} < {min_samples})"

        if df.isnull().all().any():
            cols = df.columns[df.isnull().all()].tolist()
            return False, f"Complete null columns: {cols}"

        return True, "Valid"

    def compare_models(self, models_dict, ticker):
        """
        Compare multiple models on same dataset.

        Args:
            models_dict: Dictionary {model_name: model_instance}
            ticker: Asset symbol

        Returns:
            DataFrame with comparison metrics
        """
        results = []

        for name, model in models_dict.items():
            if hasattr(model, 'results') and ticker in model.results:
                result = model.results[ticker]
                results.append({
                    'Model': name,
                    'MAE': result.get('MAE', np.nan),
                    'RMSE': result.get('RMSE', np.nan),
                    'Correlation': result.get('Correlation', np.nan)
                })

        return pd.DataFrame(results)


class VolatilityModel(BaseModel):
    """Base class for volatility forecasting models."""

    def load_data(self, ticker):
        """Load processed data with volatility features."""
        filepath = self.data_dir / f"{ticker}_features.csv"
        if not filepath.exists():
            filepath = self.data_dir / f"{ticker}_processed.csv"

        df = pd.read_csv(filepath, index_col=0, parse_dates=True)
        return df

    def get_target(self, df):
        """Extract realized volatility as prediction target."""
        if 'realized_vol_20d' in df.columns:
            return df['realized_vol_20d']
        else:
            raise ValueError("Realized volatility feature not found")


class PriceModel(BaseModel):
    """Base class for price forecasting models."""

    def load_data(self, ticker):
        """Load processed data for price forecasting."""
        filepath = self.data_dir / f"{ticker}_processed.csv"
        df = pd.read_csv(filepath, index_col=0, parse_dates=True)
        return df

    def get_target(self, df):
        """Extract close prices as prediction target."""
        if 'close' in df.columns:
            return df['close']
        else:
            raise ValueError("Close price not found")