# -*- coding: utf-8 -*-
"""arima_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smpCsZSX2TeV0zfRj3WKKMIkD8txgqdY

**Arima Model**
"""

import subprocess
import sys
subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "statsmodels"])

import pandas as pd
import numpy as np
from pathlib import Path
import warnings
from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_absolute_error, mean_squared_error

warnings.filterwarnings('ignore')

Path('results').mkdir(exist_ok=True)

class ARIMAModel:
    def __init__(self, order=(1, 1, 1)):
        self.order = order

    def load_data(self, ticker):
        filepath = f"data/processed/{ticker}_processed.csv"
        df = pd.read_csv(filepath, index_col=0, parse_dates=True)
        return df

    def split_data(self, df):
        n = len(df)
        train_end = int(n * 0.6)
        val_end = train_end + int(n * 0.2)
        return {
            'train': df.iloc[:train_end],
            'val': df.iloc[train_end:val_end],
            'test': df.iloc[val_end:]
        }

    def train_and_evaluate(self, ticker):
        print(f"ARIMA for {ticker}...", end=" ")

        try:
            df = self.load_data(ticker)
            splits = self.split_data(df)

            train_prices = splits['train']['close'].dropna()
            test_prices = splits['test']['close'].dropna()

            if len(train_prices) < 50 or len(test_prices) < 10:
                print("✗ Insufficient data")
                return

            try:
                model = ARIMA(train_prices, order=self.order)
                result = model.fit()
            except Exception as e:
                print(f"✗ Fit failed")
                return

            forecast_steps = len(test_prices)
            forecast_result = result.get_forecast(steps=forecast_steps)
            test_forecast = forecast_result.predicted_mean.values

            test_actual = test_prices.values

            mask = ~np.isnan(test_forecast)
            test_forecast = test_forecast[mask]
            test_actual = test_actual[mask]

            if len(test_forecast) == 0:
                print("✗ No valid forecasts")
                return

            mae = mean_absolute_error(test_actual, test_forecast)
            rmse = np.sqrt(mean_squared_error(test_actual, test_forecast))
            mape = np.mean(np.abs((test_actual - test_forecast) / test_actual)) * 100

            try:
                corr = np.corrcoef(test_actual, test_forecast)[0, 1]
            except:
                corr = 0.0

            forecast_df = pd.DataFrame({
                'test_actual': test_actual,
                'test_forecast': test_forecast
            }, index=test_prices.index[:len(test_actual)])

            forecast_df.to_csv(f'results/{ticker}_arima_forecast.csv')

            print(f"✓ MAE={mae:.4f}, RMSE={rmse:.4f}, MAPE={mape:.2f}%, Corr={corr:.4f}")

        except Exception as e:
            print(f"✗ {str(e)[:40]}")

print("\n" + "="*80)
print("ARIMA PRICE FORECASTING")
print("="*80 + "\n")

arima = ARIMAModel(order=(3, 1, 1))

tickers = ['SPY', 'AAPL', 'BTC-USD']

for ticker in tickers:
    arima.train_and_evaluate(ticker)

print("\n" + "="*80)
print("✓ ARIMA forecasting complete - forecasts saved to results/")
print("="*80 + "\n")

print("""
ARIMA KEY POINTS:
  - Assumes linear patterns in price movements
  - Differencing (d=1) removes trends
  - Autoregressive (p) and Moving Average (q) capture patterns

REALITY:
  - Stock prices are nearly random walk
  - Hard to beat simple baseline (yesterday's price)
  - Better for volatility forecasting
""")