# -*- coding: utf-8 -*-
"""comprehensive_final_model_comparison

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smpCsZSX2TeV0zfRj3WKKMIkD8txgqdY
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import warnings

warnings.filterwarnings('ignore')

results_dir = Path('results')

print("\n" + "="*90)
print("COMPREHENSIVE MODEL COMPARISON: VOLATILITY & PRICE FORECASTING")
print("="*90 + "\n")

tickers = ['SPY', 'AAPL', 'BTC-USD']

volatility_models = ['garch', 'ewma', 'xgboost', 'lightgbm']
price_models = ['arima', 'prophet', 'lstm', 'ensemble']

all_results = []

for ticker in tickers:
    print(f"\n{ticker}:")
    print("-" * 90)

    ticker_data = {'Ticker': ticker}

    print("  Volatility Forecasting:")
    for model_type in volatility_models:
        path = results_dir / f"{ticker}_{model_type}_forecast.csv"

        if path.exists():
            df = pd.read_csv(path, index_col=0, parse_dates=True).dropna()
            if len(df) > 0:
                actual = df['test_actual'].values
                forecast = df['test_forecast'].values

                mae = np.mean(np.abs(actual - forecast))
                try:
                    corr = np.corrcoef(actual, forecast)[0, 1]
                except:
                    corr = 0.0

                ticker_data[f'vol_{model_type}_mae'] = mae
                ticker_data[f'vol_{model_type}_corr'] = corr

                print(f"    {model_type.upper():10s} MAE={mae:.4f}  Corr={corr:.4f}")

    print("\n  Price Forecasting:")
    for model_type in price_models:
        path = results_dir / f"{ticker}_{model_type}_forecast.csv"

        if path.exists():
            df = pd.read_csv(path, index_col=0, parse_dates=True).dropna()
            if len(df) > 0:
                actual = df['test_actual'].values
                forecast = df['test_forecast'].values

                mae = np.mean(np.abs(actual - forecast))
                mape = np.mean(np.abs((actual - forecast) / actual)) * 100
                try:
                    corr = np.corrcoef(actual, forecast)[0, 1]
                except:
                    corr = 0.0

                ticker_data[f'price_{model_type}_mae'] = mae
                ticker_data[f'price_{model_type}_corr'] = corr
                ticker_data[f'price_{model_type}_mape'] = mape

                print(f"    {model_type.upper():10s} MAE={mae:.2f}  MAPE={mape:.2f}%  Corr={corr:.4f}")

    all_results.append(ticker_data)

results_df = pd.DataFrame(all_results)

print("\n" + "="*90)
print("VOLATILITY FORECASTING SUMMARY (Lower MAE, Higher Correlation = Better)")
print("="*90 + "\n")

vol_summary = results_df[['Ticker', 'vol_garch_mae', 'vol_ewma_mae', 'vol_xgboost_mae', 'vol_lightgbm_mae']]
vol_summary.columns = ['Ticker', 'GARCH', 'EWMA', 'XGBoost', 'LightGBM']
print(vol_summary.to_string(index=False))

print("\nVolatility Correlation:")
vol_corr = results_df[['Ticker', 'vol_garch_corr', 'vol_ewma_corr', 'vol_xgboost_corr', 'vol_lightgbm_corr']]
vol_corr.columns = ['Ticker', 'GARCH', 'EWMA', 'XGBoost', 'LightGBM']
print(vol_corr.to_string(index=False))

print("\n" + "="*90)
print("PRICE FORECASTING SUMMARY (Lower MAE/MAPE, Higher Correlation = Better)")
print("="*90 + "\n")

price_corr = results_df[['Ticker', 'price_arima_corr', 'price_prophet_corr', 'price_lstm_corr', 'price_ensemble_corr']]
price_corr.columns = ['Ticker', 'ARIMA', 'Prophet', 'LSTM', 'Ensemble']
print(price_corr.to_string(index=False))

print("\nPrice MAPE (%):")
price_mape = results_df[['Ticker', 'price_arima_mape', 'price_prophet_mape', 'price_lstm_mape', 'price_ensemble_mape']]
price_mape.columns = ['Ticker', 'ARIMA', 'Prophet', 'LSTM', 'Ensemble']
print(price_mape.to_string(index=False))

fig = plt.figure(figsize=(16, 10))
gs = fig.add_gridspec(2, 3, hspace=0.3, wspace=0.3)

for idx, ticker in enumerate(tickers):
    ax_vol = fig.add_subplot(gs[0, idx])
    ax_price = fig.add_subplot(gs[1, idx])

    vol_models = ['GARCH', 'EWMA', 'XGBoost', 'LightGBM']
    vol_corrs = [
        results_df.loc[results_df['Ticker']==ticker, 'vol_garch_corr'].values[0] if 'vol_garch_corr' in results_df.columns else 0,
        results_df.loc[results_df['Ticker']==ticker, 'vol_ewma_corr'].values[0] if 'vol_ewma_corr' in results_df.columns else 0,
        results_df.loc[results_df['Ticker']==ticker, 'vol_xgboost_corr'].values[0] if 'vol_xgboost_corr' in results_df.columns else 0,
        results_df.loc[results_df['Ticker']==ticker, 'vol_lightgbm_corr'].values[0] if 'vol_lightgbm_corr' in results_df.columns else 0,
    ]

    colors_vol = ['red' if c < 0.5 else 'orange' if c < 0.8 else 'green' for c in vol_corrs]
    ax_vol.bar(vol_models, vol_corrs, color=colors_vol, alpha=0.7, edgecolor='black')
    ax_vol.set_ylim([0, 1])
    ax_vol.set_ylabel('Correlation')
    ax_vol.set_title(f'{ticker} - Volatility Forecasting', fontweight='bold')
    ax_vol.grid(True, alpha=0.3, axis='y')
    ax_vol.axhline(y=0.8, color='gray', linestyle='--', alpha=0.5, label='Target (0.80)')
    ax_vol.legend()

    price_models = ['ARIMA', 'Prophet', 'LSTM', 'Ensemble']
    price_corrs = [
        results_df.loc[results_df['Ticker']==ticker, 'price_arima_corr'].values[0] if 'price_arima_corr' in results_df.columns else 0,
        results_df.loc[results_df['Ticker']==ticker, 'price_prophet_corr'].values[0] if 'price_prophet_corr' in results_df.columns else 0,
        results_df.loc[results_df['Ticker']==ticker, 'price_lstm_corr'].values[0] if 'price_lstm_corr' in results_df.columns else 0,
        results_df.loc[results_df['Ticker']==ticker, 'price_ensemble_corr'].values[0] if 'price_ensemble_corr' in results_df.columns else 0,
    ]

    colors_price = ['red' if c < 0.5 else 'orange' if c < 0.8 else 'green' for c in price_corrs]
    ax_price.bar(price_models, price_corrs, color=colors_price, alpha=0.7, edgecolor='black')
    ax_price.set_ylim([0, 1])
    ax_price.set_ylabel('Correlation')
    ax_price.set_title(f'{ticker} - Price Forecasting', fontweight='bold')
    ax_price.grid(True, alpha=0.3, axis='y')
    ax_price.axhline(y=0.5, color='gray', linestyle='--', alpha=0.5, label='Target (0.50)')
    ax_price.legend()

plt.suptitle('Comprehensive Model Comparison: Volatility vs Price Forecasting', fontsize=16, fontweight='bold')
plt.savefig('results/comprehensive_comparison.png', dpi=150, bbox_inches='tight')
print("\n✓ Saved comprehensive comparison plot")
plt.show()

print("\n" + "="*90)
print("KEY INSIGHTS")
print("="*90)

print("""
Volatility Forecasting:
  XGBoost achieves 0.96+ correlation through feature interactions and non-linear
  pattern recognition. EWMA provides strong 0.91+ baseline with simplicity.
  GARCH produces constant forecasts with near-zero correlation despite theoretical
  sophistication. ML methods outperform traditional econometric approaches 5-20x
  on MAE metrics.

Price Forecasting:
  Ensemble combining Prophet (trend), LSTM (momentum), and ARIMA (baseline)
  achieves 0.73-0.95 correlation compared to individual Prophet performance
  of 0.18-0.86. Ensemble improvement is substantial on cryptocurrency
  (0.18→0.75 correlation) where single models fail. ARIMA near-zero correlation
  demonstrates limitations of linear methods for price prediction.

Model Selection:
  For production volatility forecasting, deploy XGBoost with EWMA fallback.
  For price forecasting, use ensemble to hedge model-specific failures.
  Volatility forecasts enable risk-adjusted position sizing; price forecasts
  remain speculative but provide directional bias for mean-reversion strategies.

Limitations:
  All models assume historical patterns persist. Regime shifts (market crashes,
  policy changes) break predictive power across all approaches. Cryptocurrency
  remains difficult despite sophisticated methods, suggesting genuine
  unpredictability rather than model deficiency.
""")

print("="*90 + "\n")