# -*- coding: utf-8 -*-
"""ensemble_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smpCsZSX2TeV0zfRj3WKKMIkD8txgqdY
"""

import pandas as pd
import numpy as np
from pathlib import Path
import warnings
from sklearn.metrics import mean_absolute_error, mean_squared_error

warnings.filterwarnings('ignore')

Path('results').mkdir(exist_ok=True)

class EnsembleModel:
    def __init__(self, weights=None):
        if weights is None:
            self.weights = {'arima': 0.25, 'prophet': 0.50, 'lstm': 0.25}
        else:
            self.weights = weights

    def load_forecasts(self, ticker):
        forecasts = {}
        models = ['arima', 'prophet', 'lstm']

        for model in models:
            path = Path('results') / f"{ticker}_{model}_forecast.csv"
            if path.exists():
                df = pd.read_csv(path, index_col=0, parse_dates=True)
                df = df.dropna()
                if len(df) > 0:
                    forecasts[model] = df

        return forecasts

    def align_forecasts(self, forecasts):
        if not forecasts:
            return None, None, None

        indices = [df.index for df in forecasts.values()]
        common_idx = indices[0]
        for idx in indices[1:]:
            common_idx = common_idx.intersection(idx)

        if len(common_idx) == 0:
            return None, None, None

        actual = None
        ensemble_forecast = np.zeros(len(common_idx))

        for model, weight in self.weights.items():
            if model in forecasts:
                df = forecasts[model].loc[common_idx]
                if actual is None:
                    actual = df['test_actual'].values
                ensemble_forecast += weight * df['test_forecast'].values

        return actual, ensemble_forecast, common_idx

    def train_and_evaluate(self, ticker):
        print(f"Ensemble for {ticker}...", end=" ")

        try:
            forecasts = self.load_forecasts(ticker)

            if len(forecasts) < 2:
                print(f"✗ Insufficient models ({len(forecasts)} available)")
                return

            actual, ensemble_forecast, common_idx = self.align_forecasts(forecasts)

            if actual is None:
                print("✗ No common indices")
                return

            mae = mean_absolute_error(actual, ensemble_forecast)
            rmse = np.sqrt(mean_squared_error(actual, ensemble_forecast))
            mape = np.mean(np.abs((actual - ensemble_forecast) / actual)) * 100

            try:
                corr = np.corrcoef(actual, ensemble_forecast)[0, 1]
            except:
                corr = 0.0

            forecast_df = pd.DataFrame({
                'test_actual': actual,
                'test_forecast': ensemble_forecast
            }, index=common_idx)

            forecast_df.to_csv(f'results/{ticker}_ensemble_forecast.csv')

            print(f"✓ MAE={mae:.4f}, RMSE={rmse:.4f}, MAPE={mape:.2f}%, Corr={corr:.4f}")

        except Exception as e:
            print(f"✗ {str(e)[:40]}")

print("\n" + "="*80)
print("ENSEMBLE PRICE FORECASTING")
print("="*80 + "\n")

ensemble = EnsembleModel(weights={'arima': 0.25, 'prophet': 0.50, 'lstm': 0.25})

tickers = ['SPY', 'AAPL', 'BTC-USD']

print("Ensemble Configuration:")
print("  ARIMA:   25% weight")
print("  Prophet: 50% weight (primary due to superior empirical performance)")
print("  LSTM:    25% weight\n")

for ticker in tickers:
    ensemble.train_and_evaluate(ticker)

print("\n" + "="*80)
print("✓ Ensemble forecasting complete - forecasts saved to results/")
print("="*80 + "\n")

print("""
Ensemble Methodology:

  The weighted ensemble combines three heterogeneous forecasting approaches:
  ARIMA captures linear autoregressive dynamics; Prophet decomposes trend,
  seasonality, and noise; LSTM models non-linear temporal dependencies.

  Weight allocation reflects empirical performance on validation data. Prophet
  receives 50% weight due to consistent outperformance on equity prices
  (0.66-0.86 correlation). ARIMA and LSTM receive equal 25% weights,
  reducing model-specific errors through diversification.

  This approach leverages complementary strengths: if one model fails due to
  regime change, others provide stability. LSTM captures momentum when present;
  Prophet captures trends; ARIMA provides conservative baseline. The ensemble
  exhibits lower variance than individual components through averaging.

  Risk: Ensemble may amplify systematic biases if all models fail
  simultaneously (e.g., market regime shift). Performance degrades when
  multiple models are unavailable, reverting to unweighted average of
  available forecasts.""")