# -*- coding: utf-8 -*-
"""lstm_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smpCsZSX2TeV0zfRj3WKKMIkD8txgqdY
"""

import subprocess
import sys
subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "tensorflow"])

import pandas as pd
import numpy as np
from pathlib import Path
import warnings
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

warnings.filterwarnings('ignore')
tf.get_logger().setLevel('ERROR')

Path('results').mkdir(exist_ok=True)

class LSTMModel:
    def __init__(self, lookback=20, epochs=50):
        self.lookback = lookback
        self.epochs = epochs
        self.scaler = MinMaxScaler(feature_range=(0, 1))

    def load_data(self, ticker):
        filepath = f"data/processed/{ticker}_processed.csv"
        df = pd.read_csv(filepath, index_col=0, parse_dates=True)
        return df

    def split_data(self, df):
        n = len(df)
        train_end = int(n * 0.6)
        val_end = train_end + int(n * 0.2)
        return {
            'train': df.iloc[:train_end],
            'val': df.iloc[train_end:val_end],
            'test': df.iloc[val_end:]
        }

    def create_sequences(self, data, lookback):
        X, y = [], []
        for i in range(lookback, len(data)):
            X.append(data[i-lookback:i, 0])
            y.append(data[i, 0])
        return np.array(X), np.array(y)

    def train_and_evaluate(self, ticker):
        print(f"LSTM for {ticker}...", end=" ")

        try:
            df = self.load_data(ticker)
            splits = self.split_data(df)

            train_prices = splits['train']['close'].values.reshape(-1, 1)
            test_prices = splits['test']['close'].values.reshape(-1, 1)

            if len(train_prices) < 50 or len(test_prices) < 10:
                print("✗ Insufficient data")
                return

            train_scaled = self.scaler.fit_transform(train_prices)

            X_train, y_train = self.create_sequences(train_scaled, self.lookback)

            if len(X_train) < 10:
                print("✗ Insufficient sequences")
                return

            X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], 1))

            model = Sequential([
                LSTM(50, activation='relu', input_shape=(self.lookback, 1)),
                Dropout(0.2),
                Dense(25, activation='relu'),
                Dense(1)
            ])

            model.compile(optimizer='adam', loss='mse')

            early_stop = EarlyStopping(monitor='loss', patience=5, restore_best_weights=True)

            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                model.fit(X_train, y_train, epochs=self.epochs, batch_size=16,
                         callbacks=[early_stop], verbose=0)

            test_scaled = self.scaler.transform(test_prices)

            test_forecast = []

            for i in range(len(test_scaled)):
                if i < self.lookback:
                    lookback_data = np.concatenate([train_scaled[-(self.lookback-i):], test_scaled[:i]])
                else:
                    lookback_data = test_scaled[i-self.lookback:i]

                X_pred = lookback_data.reshape(1, self.lookback, 1)
                pred = model.predict(X_pred, verbose=0)
                test_forecast.append(pred[0, 0])

            test_forecast = np.array(test_forecast).reshape(-1, 1)
            test_forecast = self.scaler.inverse_transform(test_forecast)

            test_actual = test_prices

            mae = mean_absolute_error(test_actual, test_forecast)
            rmse = np.sqrt(mean_squared_error(test_actual, test_forecast))
            mape = np.mean(np.abs((test_actual - test_forecast) / test_actual)) * 100

            try:
                corr = np.corrcoef(test_actual.flatten(), test_forecast.flatten())[0, 1]
            except:
                corr = 0.0

            forecast_df = pd.DataFrame({
                'test_actual': test_actual.flatten(),
                'test_forecast': test_forecast.flatten()
            }, index=splits['test'].index[:len(test_actual)])

            forecast_df.to_csv(f'results/{ticker}_lstm_forecast.csv')

            print(f"✓ MAE={mae:.4f}, RMSE={rmse:.4f}, MAPE={mape:.2f}%, Corr={corr:.4f}")

        except Exception as e:
            print(f"✗ {str(e)[:40]}")

print("\n" + "="*80)
print("LSTM PRICE FORECASTING")
print("="*80 + "\n")

lstm = LSTMModel(lookback=20, epochs=50)

tickers = ['SPY', 'AAPL', 'BTC-USD']

for ticker in tickers:
    lstm.train_and_evaluate(ticker)

print("\n" + "="*80)
print("✓ LSTM forecasting complete - forecasts saved to results/")
print("="*80 + "\n")

print("""
LSTM Architecture:
  - Input: 20-day price sequences normalized to [0,1]
  - Layer 1: LSTM(50) with ReLU activation captures temporal dependencies
  - Layer 2: Dropout(0.2) regularizes to prevent overfitting on limited data
  - Layer 3: Dense(25) with ReLU maps learned representations
  - Output: Single-step price prediction via Dense(1)

Training:
  - Optimizer: Adam with default learning rate
  - Loss: Mean squared error
  - Early stopping: Patience=5 on training loss to prevent overfitting
  - Batch size: 16 sequences per gradient update

Market Dynamics:
  The LSTM approach assumes price movements exhibit learnable non-linear patterns
  through historical price sequences. In practice, the architecture may capture
  momentum and mean reversion effects but faces fundamental constraints imposed
  by the efficient market hypothesis. The lookback window of 20 trading days
  reflects the estimated information decay in price memory.""")