# -*- coding: utf-8 -*-
"""prophet_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smpCsZSX2TeV0zfRj3WKKMIkD8txgqdY
"""

import subprocess
import sys
subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "prophet"])

import pandas as pd
import numpy as np
from pathlib import Path
import warnings
from prophet import Prophet
from sklearn.metrics import mean_absolute_error, mean_squared_error

warnings.filterwarnings('ignore')

Path('results').mkdir(exist_ok=True)

class ProphetModel:
    def load_data(self, ticker):
        filepath = f"data/processed/{ticker}_processed.csv"
        df = pd.read_csv(filepath, index_col=0, parse_dates=True)
        return df

    def split_data(self, df):
        n = len(df)
        train_end = int(n * 0.6)
        val_end = train_end + int(n * 0.2)
        return {
            'train': df.iloc[:train_end],
            'val': df.iloc[train_end:val_end],
            'test': df.iloc[val_end:]
        }

    def train_and_evaluate(self, ticker):
        print(f"Prophet for {ticker}...", end=" ")

        try:
            df = self.load_data(ticker)
            splits = self.split_data(df)

            train_data = splits['train'][['close']].reset_index()
            train_data.columns = ['ds', 'y']

            test_data = splits['test'][['close']].reset_index()
            test_data.columns = ['ds', 'y']

            if len(train_data) < 50 or len(test_data) < 10:
                print("✗ Insufficient data")
                return

            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                model = Prophet(yearly_seasonality=False, daily_seasonality=False, interval_width=0.95)
                model.fit(train_data)

            future = test_data[['ds']].copy()
            forecast = model.predict(future)

            test_actual = test_data['y'].values
            test_forecast = forecast['yhat'].values

            mask = ~np.isnan(test_forecast)
            test_forecast = test_forecast[mask]
            test_actual = test_actual[mask]

            if len(test_forecast) == 0:
                print("✗ No valid forecasts")
                return

            mae = mean_absolute_error(test_actual, test_forecast)
            rmse = np.sqrt(mean_squared_error(test_actual, test_forecast))
            mape = np.mean(np.abs((test_actual - test_forecast) / test_actual)) * 100

            try:
                corr = np.corrcoef(test_actual, test_forecast)[0, 1]
            except:
                corr = 0.0

            forecast_df = pd.DataFrame({
                'test_actual': test_actual,
                'test_forecast': test_forecast
            }, index=test_data['ds'][:len(test_actual)].values)

            forecast_df.to_csv(f'results/{ticker}_prophet_forecast.csv')

            print(f"✓ MAE={mae:.4f}, RMSE={rmse:.4f}, MAPE={mape:.2f}%, Corr={corr:.4f}")

        except Exception as e:
            print(f"✗ {str(e)[:40]}")

print("\n" + "="*80)
print("PROPHET PRICE FORECASTING")
print("="*80 + "\n")

prophet = ProphetModel()

tickers = ['SPY', 'AAPL', 'BTC-USD']

for ticker in tickers:
    prophet.train_and_evaluate(ticker)

print("\n" + "="*80)
print("✓ Prophet forecasting complete - forecasts saved to results/")
print("="*80 + "\n")

print("""
PROPHET KEY POINTS:
  - Additive decomposition: Trend + Seasonality + Holidays
  - Good for time series with strong trends and seasonality
  - Less sensitive to outliers than ARIMA
  - Easier to tune (fewer parameters)

STOCK PRICES:
  - No real seasonality (no Monday effect, etc.)
  - Trend changes unpredictably
  - Still hard to beat random walk
""")